tubo_new: 
    path: /new
    defaults: { _controller: "AppBundle:Tubo:new"}
    methods: POST

tubo_edit:
    path: /edit/{id}
    defaults: { _controller: "AppBundle:Tubo:edit", id:null}
    methods: POST

tubo_delete:
    path: /delete/{id}
    defaults: { _controller: "AppBundle:Tubo:delete", id:null}
    methods: POST