BackendBundle\Entity\Canaleta:
    type: entity
    table: canaleta
    indexes:
        fk_canaleta_canaleta_tipo_idx:
            columns:
                - canaleta_tipo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        area:
            type: float
            nullable: true
            precision: 10
            scale: 0
    manyToOne:
        canaletaTipo:
            targetEntity: CanaletaTipo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                canaleta_tipo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
