BackendBundle\Entity\Proyectos:
    type: entity
    table: proyectos
    indexes:
        fk_proyecto_usuario_idx:
            columns:
                - usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        pdf:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
